In [1]:
import numpy as np 
numbers = np.arange(1,101)
print("Numbers : ")
print(numbers)

Numbers : 
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [2]:
import numpy as np

# Create a 4x4 2D array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

print("2D Array:")
print(arr)

# Average of each row
row_avg = np.mean(arr, axis=1)
print("\nAverage of each row:")
print(row_avg)

# Average of each column
column_avg = np.mean(arr, axis=0)
print("\nAverage of each column:")
print(column_avg)

# Standard deviation of the entire array
std = np.std(arr)
print("\nStandard Deviation:")
print(std)

2D Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Average of each row:
[ 2.5  6.5 10.5 14.5]

Average of each column:
[ 7.  8.  9. 10.]

Standard Deviation:
4.6097722286464435


In [3]:
import numpy as np

# Create 4x4 array with random numbers from 1 to 100
arr = np.random.randint(1, 101, size=(10, 10))

print("Random 2D Array:")
print(arr)

# Average of each row
row_avg = np.mean(arr, axis=1)
print("\nAverage of each row:")
print(row_avg)

# Average of each column
column_avg = np.mean(arr, axis=0)
print("\nAverage of each column:")
print(column_avg)

# Standard deviation of entire array
std = np.std(arr)
print("\nStandard Deviation:")
print(std)

Random 2D Array:
[[ 29  57  72  30  70  92  41  70  38  87]
 [ 13  54   7  38  66  38  87  45  95  29]
 [ 27  62  14  37   5   4  49   1  26   7]
 [ 54  46  97   2  26   9  21  59  79  79]
 [ 25  67  25  86  12  38  81  29   6  25]
 [ 54  47  82  54  60  36  40  62  32  10]
 [ 37  51  36  31 100  53  79  81  23  41]
 [ 77  49  95  47  76  34 100  76  90  27]
 [ 16  53  26  86  83   5  27  56  71  93]
 [ 70  34  82  53  64  14  50  28   8  63]]

Average of each row:
[58.6 47.2 23.2 47.2 39.4 47.7 53.2 67.1 51.6 46.6]

Average of each column:
[40.2 52.  53.6 46.4 56.2 32.3 57.5 50.7 46.8 46.1]

Standard Deviation:
27.33473248451501
